version: '3.8'
services:
  php-apache-environment:
    container_name: php-apache
    build:
        context: .
        dockerfile: Dockerfile
    image: getting-started
    depends_on:
        - db
    volumes:
        - .:/var/www/laravel_docker
        - ./php/php.ini:/usr/local/etc/php/conf.d/docker-php-ext-sodium.ini
        - ./services/apache/default.conf:/etc/apache2/apache2.conf
        #- ./services/apache/default.conf:/etc/apache2/sites-enabled/000-default.conf
    ports:
          - 8000:80
  db:
    container_name: db
    image: mysql
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
        MYSQL_DATABASE: MYSQL_DATABASE
        MYSQL_USER: MYSQL_USER
        MYSQL_PASSWORD: MYSQL_PASSWORD
    ports:
      - "3306:3306"
    volumes:
      - mysql-volume:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
        - '8080:80'
    restart: always
    environment:
        PMA_HOST: db
    depends_on:
        - db
  portainer:
    image: portainer/portainer
    ports:
        - 9000:9000
    command: -H unix:///var/run/docker.sock
    deploy:
        mode: replicated
        replicas: 1
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - ./services/portainer/data:/data 
        - '/etc/localtime:/etc/localtime:ro'
volumes:
  mysql-volume: